# Use a base Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the script and environment files into the container
COPY bitcoin.py ./
COPY .env ./


# Set the default command to run your script
CMD ["python", "bitcoin.py"]